### ISSUE TITLE
"Management" is the name of account that is assumed in the manifest.yaml

### ISSUE THREAD

**Issue by vhartikainen** [aws-samples/aws-ct-vpc-flowlogs#17]
In `manifest.yaml`, when  creating the VPCFlowLogRole in Management account, it's assumed that the ControlTower Management account is named `Management`. This might not be the case.

```
  - name: VPCFlowLogsMgmtRole
    resource_file: vpcflowlogs/templates/vpc_flowlog_mgmt.template
    parameters:
      - parameter_key: "OrganizationId"
        parameter_value: "$[alfred_ssm_/org/core/OrganizationID]" 

      - parameter_key: "EventBusDestinationAccount" # Typiclly this will be the NetworkHub account
        parameter_value: "478239160000"

      - parameter_key: "BaselineCloudTrailStackArn" # Copy this this from mgmt account in cloudformation stacksets for AWSControlTowerBP-BASELINE-CLOUDTRAIL
        parameter_value: "arn:aws:cloudformation:eu-west-1:607614377744:stackset/AWSControlTowerBP-BASELINE-CLOUDTRAIL:f70b1254-9d9b-42b6-bedb-59a936647f6a"
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - Management
    regions:
      - eu-west-1
```
